[application]
name = "Commission Manager"
client_id = "e81a378169460e05b6dc74fe0bce85b0"
application_url = "https://twiva-commerce-shopify.vercel.app"
embedded = true

[application.pos]
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_collections"

[auth]
redirect_urls = [
  "https://twiva-commerce-shopify.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"
