[application]
name = "Commission Manager"
client_id = "81e3caa4c1e56b7c9dc6a25bd2e78853"
application_url = "https://twiva-commerce-shopify.vercel.app"
embedded = true

[application.pos]
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_collections"

[auth]
redirect_urls = [
  "https://twiva-commerce-shopify.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"
